language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - node_modules
before_script: npm run build
after_success: npm run coverage
after_script:
  # - npm run jest -- -u
  - npm run artifacts
