name: Checks
on:
  pull_request:
    branches:
      - master
jobs:
  size:
    runs-on: ubuntu-latest
    name: size-limit
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 7
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Check size
        uses: andresz1/size-limit-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  editorconfig:
    runs-on: ubuntu-latest
    name: editorconfig
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Create config
        run: |
          echo '{"Exclude": ["docs", ".git"]}' > .ecrc
      - name: Check editorconfig
        uses: editorconfig-checker/action-editorconfig-checker@v1
  package-json:
    runs-on: ubuntu-latest
    name: package.json
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 7
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Check package.json files
        run: pnpm --package=@trigen/lint-package-json dlx lint-package-json --ignore sandboxes --ignore website
