name: Update snapshots
on: workflow_dispatch
jobs:
  update-snapshots:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage:
          - browser
          - node
          - offscreen
      fail-fast: false
    name: ${{ matrix.stage }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 7
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
        env:
          NODE_ENV: 'development'
      - name: Update snapshots
        run: |
          pnpm test:${{ matrix.stage }} -- -- -u
          pnpm del 'test/__image_snapshots__/*.png' '!test/__image_snapshots__/${{ matrix.stage }}*'
      - name: Collect artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Updated image snapshots (${{ matrix.stage }})
          path: test/__image_snapshots__/
